// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polyarray.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Segment compress elements with several polynomials.
// Number of elements in a Segment must be power of 2 in order to speed up
// Get().
//
// Since 0.5.2
type Segment struct {
	Polynomials          []float64 `protobuf:"fixed64,1,rep,packed,name=Polynomials,proto3" json:"Polynomials,omitempty"`
	Starts               []int32   `protobuf:"varint,2,rep,packed,name=Starts,proto3" json:"Starts,omitempty"`
	Words                []int64   `protobuf:"varint,3,rep,packed,name=Words,proto3" json:"Words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_polyarray_a55dbf429c4030bb, []int{0}
}
func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (dst *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(dst, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetPolynomials() []float64 {
	if m != nil {
		return m.Polynomials
	}
	return nil
}

func (m *Segment) GetStarts() []int32 {
	if m != nil {
		return m.Starts
	}
	return nil
}

func (m *Segment) GetWords() []int64 {
	if m != nil {
		return m.Words
	}
	return nil
}

// PolyArray uses one or more polynomial to compress and store an array of int64.
//
// Since 0.5.2
type PolyArray struct {
	//   wordsize = 64
	//   wordsize / EltWidth = word capacity
	EltWidth             uint32     `protobuf:"varint,1,opt,name=EltWidth,proto3" json:"EltWidth,omitempty"`
	EltMask              int32      `protobuf:"varint,2,opt,name=EltMask,proto3" json:"EltMask,omitempty"`
	WordCapWidth         uint32     `protobuf:"varint,3,opt,name=WordCapWidth,proto3" json:"WordCapWidth,omitempty"`
	WordCapMask          int32      `protobuf:"varint,4,opt,name=WordCapMask,proto3" json:"WordCapMask,omitempty"`
	SegWidth             uint32     `protobuf:"varint,5,opt,name=SegWidth,proto3" json:"SegWidth,omitempty"`
	SegMask              int32      `protobuf:"varint,6,opt,name=SegMask,proto3" json:"SegMask,omitempty"`
	N                    int32      `protobuf:"varint,10,opt,name=N,proto3" json:"N,omitempty"`
	Segments             []*Segment `protobuf:"bytes,20,rep,name=Segments,proto3" json:"Segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PolyArray) Reset()         { *m = PolyArray{} }
func (m *PolyArray) String() string { return proto.CompactTextString(m) }
func (*PolyArray) ProtoMessage()    {}
func (*PolyArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_polyarray_a55dbf429c4030bb, []int{1}
}
func (m *PolyArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolyArray.Unmarshal(m, b)
}
func (m *PolyArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolyArray.Marshal(b, m, deterministic)
}
func (dst *PolyArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolyArray.Merge(dst, src)
}
func (m *PolyArray) XXX_Size() int {
	return xxx_messageInfo_PolyArray.Size(m)
}
func (m *PolyArray) XXX_DiscardUnknown() {
	xxx_messageInfo_PolyArray.DiscardUnknown(m)
}

var xxx_messageInfo_PolyArray proto.InternalMessageInfo

func (m *PolyArray) GetEltWidth() uint32 {
	if m != nil {
		return m.EltWidth
	}
	return 0
}

func (m *PolyArray) GetEltMask() int32 {
	if m != nil {
		return m.EltMask
	}
	return 0
}

func (m *PolyArray) GetWordCapWidth() uint32 {
	if m != nil {
		return m.WordCapWidth
	}
	return 0
}

func (m *PolyArray) GetWordCapMask() int32 {
	if m != nil {
		return m.WordCapMask
	}
	return 0
}

func (m *PolyArray) GetSegWidth() uint32 {
	if m != nil {
		return m.SegWidth
	}
	return 0
}

func (m *PolyArray) GetSegMask() int32 {
	if m != nil {
		return m.SegMask
	}
	return 0
}

func (m *PolyArray) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *PolyArray) GetSegments() []*Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func init() {
	proto.RegisterType((*Segment)(nil), "Segment")
	proto.RegisterType((*PolyArray)(nil), "PolyArray")
}

func init() { proto.RegisterFile("polyarray.proto", fileDescriptor_polyarray_a55dbf429c4030bb) }

var fileDescriptor_polyarray_a55dbf429c4030bb = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0xc9, 0xa4, 0x33, 0xad, 0xaf, 0x15, 0xe1, 0x51, 0xe4, 0xe1, 0x2a, 0x0c, 0x2e, 0xb2,
	0xea, 0x42, 0xbf, 0x40, 0xa5, 0x4b, 0x8b, 0x64, 0x16, 0x45, 0x77, 0x29, 0x1d, 0xc6, 0x62, 0xda,
	0x0c, 0x49, 0x36, 0xf3, 0xd9, 0xfe, 0x81, 0x24, 0x99, 0x96, 0xba, 0x3c, 0x37, 0xdc, 0x7b, 0xc2,
	0x83, 0xbb, 0xde, 0x9a, 0x41, 0x3b, 0xa7, 0x87, 0x55, 0xef, 0x6c, 0xb0, 0xf5, 0x27, 0x4c, 0x9b,
	0xb6, 0x3b, 0xb6, 0xa7, 0x80, 0x02, 0xe6, 0x1f, 0xd6, 0x0c, 0x27, 0x7b, 0x3c, 0x68, 0xe3, 0x89,
	0x09, 0x2e, 0x99, 0xba, 0x8e, 0xf0, 0x1e, 0xaa, 0x26, 0x68, 0x17, 0x3c, 0x15, 0x82, 0xcb, 0x52,
	0x8d, 0x84, 0x4b, 0x28, 0xb7, 0xd6, 0xed, 0x3d, 0x71, 0xc1, 0x25, 0x57, 0x19, 0xea, 0x5f, 0x06,
	0x37, 0xb1, 0xfd, 0x12, 0x75, 0xf8, 0x00, 0xb3, 0xb5, 0x09, 0xdb, 0xc3, 0x3e, 0x7c, 0x13, 0x13,
	0x4c, 0xde, 0xaa, 0x0b, 0x23, 0xc1, 0x74, 0x6d, 0xc2, 0xbb, 0xf6, 0x3f, 0x54, 0x08, 0x26, 0x4b,
	0x75, 0x46, 0xac, 0x61, 0x11, 0xc7, 0xde, 0x74, 0x9f, 0x9b, 0x3c, 0x35, 0xff, 0x65, 0xf1, 0xdf,
	0x23, 0xa7, 0x85, 0x49, 0x5a, 0xb8, 0x8e, 0xa2, 0xbb, 0x69, 0xbb, 0xbc, 0x50, 0x66, 0xf7, 0x99,
	0xa3, 0xbb, 0x69, 0xbb, 0xd4, 0xac, 0xb2, 0x7b, 0x44, 0x5c, 0x00, 0xdb, 0x10, 0xa4, 0x8c, 0x6d,
	0xf0, 0x31, 0x6d, 0xc4, 0x43, 0x79, 0x5a, 0x0a, 0x2e, 0xe7, 0x4f, 0xb3, 0xd5, 0x18, 0xa8, 0xcb,
	0xcb, 0xeb, 0xe4, 0xab, 0xe8, 0x77, 0xbb, 0x2a, 0xdd, 0xf6, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x7d, 0x2a, 0xb8, 0x6e, 0x01, 0x00, 0x00,
}
