// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodes.proto

package trie

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Bitmap is an array of bits.
//
// Since 0.5.10
type Bitmap struct {
	// Words contains bitmap
	//
	// Since 0.5.10
	Words []uint64 `protobuf:"varint,20,rep,packed,name=Words,proto3" json:"Words,omitempty"`
	// RankIndex speeds up rank() by pre-calcuate it
	//
	// Since 0.5.10
	RankIndex []int32 `protobuf:"varint,30,rep,packed,name=RankIndex,proto3" json:"RankIndex,omitempty"`
	// SelectIndex speeds up select() by pre-calcuate it
	//
	// Since 0.5.10
	SelectIndex          []int32  `protobuf:"varint,40,rep,packed,name=SelectIndex,proto3" json:"SelectIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bitmap) Reset()         { *m = Bitmap{} }
func (m *Bitmap) String() string { return proto.CompactTextString(m) }
func (*Bitmap) ProtoMessage()    {}
func (*Bitmap) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_d87be1751d89eed1, []int{0}
}
func (m *Bitmap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bitmap.Unmarshal(m, b)
}
func (m *Bitmap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bitmap.Marshal(b, m, deterministic)
}
func (dst *Bitmap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bitmap.Merge(dst, src)
}
func (m *Bitmap) XXX_Size() int {
	return xxx_messageInfo_Bitmap.Size(m)
}
func (m *Bitmap) XXX_DiscardUnknown() {
	xxx_messageInfo_Bitmap.DiscardUnknown(m)
}

var xxx_messageInfo_Bitmap proto.InternalMessageInfo

func (m *Bitmap) GetWords() []uint64 {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *Bitmap) GetRankIndex() []int32 {
	if m != nil {
		return m.RankIndex
	}
	return nil
}

func (m *Bitmap) GetSelectIndex() []int32 {
	if m != nil {
		return m.SelectIndex
	}
	return nil
}

// VLenArray stores var-length []byte elts.
//
// Since 0.5.10
type VLenArray struct {
	// N is the max set bit index plus 1.
	//
	// Since 0.5.10
	N int32 `protobuf:"varint,10,opt,name=N,proto3" json:"N,omitempty"`
	// EltCnt is the number of present elts.
	//
	// Since 0.5.10
	EltCnt int32 `protobuf:"varint,11,opt,name=EltCnt,proto3" json:"EltCnt,omitempty"`
	// PresenceBM set 1 at the i-th bit if the i-th elt presents.
	//
	// Since 0.5.10
	PresenceBM *Bitmap `protobuf:"bytes,61,opt,name=PresenceBM,proto3" json:"PresenceBM,omitempty"`
	// PositionBM is a bitmap of starting position of every present elt.
	//
	// Since 0.5.10
	PositionBM *Bitmap `protobuf:"bytes,20,opt,name=PositionBM,proto3" json:"PositionBM,omitempty"`
	// FixedSize is set to elt size in Bytes field, if all the elts have equal sizes.
	//
	// Since 0.5.10
	FixedSize int32 `protobuf:"varint,23,opt,name=FixedSize,proto3" json:"FixedSize,omitempty"`
	// Bytes is the content in bytes
	//
	// Since 0.5.10
	Bytes                []byte   `protobuf:"bytes,30,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VLenArray) Reset()         { *m = VLenArray{} }
func (m *VLenArray) String() string { return proto.CompactTextString(m) }
func (*VLenArray) ProtoMessage()    {}
func (*VLenArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_d87be1751d89eed1, []int{1}
}
func (m *VLenArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VLenArray.Unmarshal(m, b)
}
func (m *VLenArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VLenArray.Marshal(b, m, deterministic)
}
func (dst *VLenArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VLenArray.Merge(dst, src)
}
func (m *VLenArray) XXX_Size() int {
	return xxx_messageInfo_VLenArray.Size(m)
}
func (m *VLenArray) XXX_DiscardUnknown() {
	xxx_messageInfo_VLenArray.DiscardUnknown(m)
}

var xxx_messageInfo_VLenArray proto.InternalMessageInfo

func (m *VLenArray) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *VLenArray) GetEltCnt() int32 {
	if m != nil {
		return m.EltCnt
	}
	return 0
}

func (m *VLenArray) GetPresenceBM() *Bitmap {
	if m != nil {
		return m.PresenceBM
	}
	return nil
}

func (m *VLenArray) GetPositionBM() *Bitmap {
	if m != nil {
		return m.PositionBM
	}
	return nil
}

func (m *VLenArray) GetFixedSize() int32 {
	if m != nil {
		return m.FixedSize
	}
	return 0
}

func (m *VLenArray) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

// Nodes is array of all inner nodes in slim trie.
// It is NOT a public type and do not rely on it.
// Since protobuf just makes all message public.
//
// Since 0.5.10
type Nodes struct {
	// BigInnerCnt is number of big (267 bit) inner node.
	//
	// Since 0.5.10
	BigInnerCnt int32 `protobuf:"varint,11,opt,name=BigInnerCnt,proto3" json:"BigInnerCnt,omitempty"`
	// BigInnerOffset is the offset caused by "BigInner" nodes:
	//
	// Supposing that the i-th inner node is the j-th short inner node(an inner
	// node can be a short).
	//
	// The offset of this node in "Inners" is
	//
	//     257 * BigInnerCnt +
	//     17 * (i-BigInnerCnt-j) +
	//     ShortSize * j
	//
	// Thus we could create 2 variables to reduce offset calculation time:
	//
	//     BigInnerOffset = (257 - 17) * BigInnerCnt
	//     ShortMinusInner = ShortSize - 17
	//
	// The the offset is:
	//
	//     BigInnerOffset + 17 * i + ShortMinusInner * j
	//
	// Since 0.5.10
	BigInnerOffset int32 `protobuf:"varint,12,opt,name=BigInnerOffset,proto3" json:"BigInnerOffset,omitempty"`
	// ShortMinusInner is ShortSize minus 17.
	// See BigInnerOffset.
	//
	// Since 0.5.10
	ShortMinusInner int32 `protobuf:"varint,13,opt,name=ShortMinusInner,proto3" json:"ShortMinusInner,omitempty"`
	// ShortSize is the number of bit of short bitmap that reduce most memory
	// cost.
	//
	// Since 0.5.10
	ShortSize int32 `protobuf:"varint,14,opt,name=ShortSize,proto3" json:"ShortSize,omitempty"`
	// ShortMask has the lower ShortSize bit set to 1.
	//
	// Since 0.5.10
	ShortMask uint64 `protobuf:"varint,15,opt,name=ShortMask,proto3" json:"ShortMask,omitempty"`
	// NodeTypeBM is a bitmap in which a "1" indicates the i-th node is an inner
	// node, otherwise it is a leaf.
	//
	// Since 0.5.10
	NodeTypeBM *Bitmap `protobuf:"bytes,20,opt,name=NodeTypeBM,proto3" json:"NodeTypeBM,omitempty"`
	// Inners is a array of var-length node label bitmaps.
	// The size of an element bitmap is aligned to 4.
	//
	// Since 0.5.10
	Inners *Bitmap `protobuf:"bytes,30,opt,name=Inners,proto3" json:"Inners,omitempty"`
	// ShortBM indicate most used inner node bitmaps.
	// These nodes takes 4 bits and the actual bitmaps are stored separate.
	//
	// Since 0.5.10
	ShortBM *Bitmap `protobuf:"bytes,31,opt,name=ShortBM,proto3" json:"ShortBM,omitempty"`
	// ShortTable is a mapping of short bitmap to full 17-bit bitmap.
	//
	// Since 0.5.10
	ShortTable []uint32 `protobuf:"varint,32,rep,packed,name=ShortTable,proto3" json:"ShortTable,omitempty"`
	// InnerPrefixes of inner nodes.
	// There are two usages with this field:
	// - If inner node prefix is stored, it is a var-len array of stored prefix string.
	// - If only inner node prefix length is stored, it is a array with fixed-size elts. An array elt is the length in 4-bit of a prefix.
	//
	// In full-prefix mode:
	// An array element is a control byte followed by several data bytes.
	//
	// The 0-th bit in the control byte indicates whether a prefix is
	// trucated(not aligned to 8-bit).
	//
	// An inner node may have a prefix, if the starting bit of the node > the end
	// of previous node.
	//
	// The end of a prefix may not be 8-bit aligned.
	// Thus we need a bitmap to indicated this.
	// If prefix length is not 8-bit aligned, the trailing bits a filled with a
	// "1" followed by "0"s.
	// To retrieve the acturate prefix, remove the bits from the last "1".
	// E.g.:
	//
	//   prefix:                  11001100 11000011
	//   stored prefix:  00000000 11001100 11010011;  control byte = 0
	//
	//   prefix:                  11001100 110
	//   stored prefix:  00000001 11001100 11010000;  control byte = 1
	//
	// Since 0.5.10
	InnerPrefixes *VLenArray `protobuf:"bytes,38,opt,name=InnerPrefixes,proto3" json:"InnerPrefixes,omitempty"`
	// LeafPrefixes stores prefix of every leaf if it is not nil.
	// A leaf prefix unlike inner node prefix, is just a byte sequence, without a control byte.
	//
	// Since 0.5.10
	LeafPrefixes *VLenArray `protobuf:"bytes,58,opt,name=LeafPrefixes,proto3" json:"LeafPrefixes,omitempty"`
	// Leaves stores serialized leaf values.
	//
	// Since 0.5.10
	Leaves               *VLenArray `protobuf:"bytes,60,opt,name=Leaves,proto3" json:"Leaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_d87be1751d89eed1, []int{2}
}
func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (dst *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(dst, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetBigInnerCnt() int32 {
	if m != nil {
		return m.BigInnerCnt
	}
	return 0
}

func (m *Nodes) GetBigInnerOffset() int32 {
	if m != nil {
		return m.BigInnerOffset
	}
	return 0
}

func (m *Nodes) GetShortMinusInner() int32 {
	if m != nil {
		return m.ShortMinusInner
	}
	return 0
}

func (m *Nodes) GetShortSize() int32 {
	if m != nil {
		return m.ShortSize
	}
	return 0
}

func (m *Nodes) GetShortMask() uint64 {
	if m != nil {
		return m.ShortMask
	}
	return 0
}

func (m *Nodes) GetNodeTypeBM() *Bitmap {
	if m != nil {
		return m.NodeTypeBM
	}
	return nil
}

func (m *Nodes) GetInners() *Bitmap {
	if m != nil {
		return m.Inners
	}
	return nil
}

func (m *Nodes) GetShortBM() *Bitmap {
	if m != nil {
		return m.ShortBM
	}
	return nil
}

func (m *Nodes) GetShortTable() []uint32 {
	if m != nil {
		return m.ShortTable
	}
	return nil
}

func (m *Nodes) GetInnerPrefixes() *VLenArray {
	if m != nil {
		return m.InnerPrefixes
	}
	return nil
}

func (m *Nodes) GetLeafPrefixes() *VLenArray {
	if m != nil {
		return m.LeafPrefixes
	}
	return nil
}

func (m *Nodes) GetLeaves() *VLenArray {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func init() {
	proto.RegisterType((*Bitmap)(nil), "Bitmap")
	proto.RegisterType((*VLenArray)(nil), "VLenArray")
	proto.RegisterType((*Nodes)(nil), "Nodes")
}

func init() { proto.RegisterFile("nodes.proto", fileDescriptor_nodes_d87be1751d89eed1) }

var fileDescriptor_nodes_d87be1751d89eed1 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x15, 0xa5, 0xc9, 0x6a, 0x27, 0xe9, 0xae, 0x64, 0x55, 0xe0, 0x03, 0xea, 0x9a, 0x1c,
	0x16, 0x9f, 0x22, 0x04, 0x37, 0x04, 0x07, 0x82, 0x40, 0x5a, 0xa9, 0x29, 0x2b, 0x77, 0x05, 0x12,
	0x07, 0xa4, 0xec, 0x66, 0x02, 0x56, 0x8b, 0x53, 0xd9, 0x06, 0xb5, 0xbc, 0x18, 0xef, 0xc0, 0x53,
	0xa1, 0x38, 0x6d, 0x92, 0xb6, 0xdc, 0x3c, 0xdf, 0xff, 0x7b, 0xfc, 0xcf, 0xc8, 0x10, 0xa9, 0xba,
	0x44, 0x93, 0xae, 0x75, 0x6d, 0xeb, 0xe4, 0x2b, 0x84, 0x99, 0xb4, 0x3f, 0x8a, 0x35, 0x99, 0x40,
	0xf0, 0xb9, 0xd6, 0xa5, 0xa1, 0x13, 0xe6, 0xf3, 0x91, 0x68, 0x0b, 0xf2, 0x04, 0xce, 0x45, 0xa1,
	0x96, 0x37, 0xaa, 0xc4, 0x0d, 0x9d, 0x32, 0x9f, 0x07, 0xa2, 0x07, 0x84, 0x41, 0xb4, 0xc0, 0x15,
	0x3e, 0xd8, 0x56, 0xe7, 0x4e, 0x1f, 0xa2, 0xe4, 0x8f, 0x07, 0xe7, 0x9f, 0x66, 0xa8, 0xde, 0x6a,
	0x5d, 0x6c, 0x49, 0x0c, 0xde, 0x9c, 0x02, 0xf3, 0x78, 0x20, 0xbc, 0x39, 0x79, 0x04, 0xe1, 0xfb,
	0x95, 0x7d, 0xa7, 0x2c, 0x8d, 0x1c, 0xda, 0x55, 0xe4, 0x19, 0xc0, 0xad, 0x46, 0x83, 0xea, 0x01,
	0xb3, 0x9c, 0xbe, 0x61, 0x1e, 0x8f, 0x5e, 0x9c, 0xa5, 0x6d, 0x4c, 0x31, 0x90, 0x9c, 0xb1, 0x36,
	0xd2, 0xca, 0x5a, 0x65, 0x39, 0x9d, 0x1c, 0x1b, 0x3b, 0xa9, 0x99, 0xe2, 0x83, 0xdc, 0x60, 0xb9,
	0x90, 0xbf, 0x91, 0x3e, 0x76, 0x8f, 0xf5, 0xa0, 0x99, 0x3c, 0xdb, 0x5a, 0x34, 0x74, 0xca, 0x3c,
	0x1e, 0x8b, 0xb6, 0x48, 0xfe, 0xfa, 0x10, 0xcc, 0x9b, 0x4d, 0x35, 0x53, 0x66, 0xf2, 0xdb, 0x8d,
	0x52, 0xa8, 0xfb, 0xb0, 0x43, 0x44, 0xae, 0xe1, 0x62, 0x5f, 0x7e, 0xac, 0x2a, 0x83, 0x96, 0xc6,
	0xce, 0x74, 0x44, 0x09, 0x87, 0xcb, 0xc5, 0xf7, 0x5a, 0xdb, 0x5c, 0xaa, 0x9f, 0xc6, 0x09, 0x74,
	0xec, 0x8c, 0xc7, 0xb8, 0x49, 0xec, 0x90, 0x4b, 0x7c, 0xd1, 0x26, 0xee, 0x40, 0xa7, 0xe6, 0x85,
	0x59, 0xd2, 0x4b, 0xe6, 0xf1, 0x91, 0xe8, 0x41, 0xb3, 0x96, 0x26, 0xf8, 0xdd, 0x76, 0x8d, 0xff,
	0x59, 0x4b, 0x2f, 0x91, 0x2b, 0x08, 0xdd, 0x6b, 0xed, 0xe4, 0x03, 0xd3, 0x0e, 0x93, 0xa7, 0x70,
	0xe6, 0xda, 0x66, 0x39, 0xbd, 0x3a, 0x74, 0xec, 0x39, 0x99, 0x02, 0xb8, 0xe3, 0x5d, 0x71, 0xbf,
	0x42, 0xca, 0x98, 0xcf, 0xc7, 0x62, 0x40, 0xc8, 0x73, 0x18, 0xbb, 0x66, 0xb7, 0x1a, 0x2b, 0xb9,
	0x41, 0x43, 0xaf, 0x5d, 0x23, 0x48, 0xbb, 0x5f, 0x21, 0x0e, 0x0d, 0x24, 0x85, 0x78, 0x86, 0x45,
	0xd5, 0x5d, 0x78, 0x75, 0x72, 0xe1, 0x40, 0x27, 0x09, 0x84, 0x33, 0x2c, 0x7e, 0xa1, 0xa1, 0xaf,
	0x4f, 0x9c, 0x3b, 0x25, 0x0b, 0xbf, 0x8c, 0xac, 0x96, 0x78, 0x1f, 0xba, 0x5f, 0xff, 0xf2, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x8c, 0x3a, 0x89, 0x04, 0x03, 0x00, 0x00,
}
