// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polyarray.proto

package array

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Segment compress elements with several polynomials.
// Number of elements in a Segment must be power of 2 in order to speed up
// Get().
//
// Since 0.5.2
type Segment struct {
	PolySpan             int32     `protobuf:"varint,5,opt,name=PolySpan,proto3" json:"PolySpan,omitempty"`
	PolySpanWidth        uint32    `protobuf:"varint,6,opt,name=PolySpanWidth,proto3" json:"PolySpanWidth,omitempty"`
	Polynomials          []float64 `protobuf:"fixed64,10,rep,packed,name=Polynomials,proto3" json:"Polynomials,omitempty"`
	Info                 []uint32  `protobuf:"varint,11,rep,packed,name=Info,proto3" json:"Info,omitempty"`
	Words                []int64   `protobuf:"varint,20,rep,packed,name=Words,proto3" json:"Words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_polyarray_42001cec0af51f9f, []int{0}
}
func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (dst *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(dst, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetPolySpan() int32 {
	if m != nil {
		return m.PolySpan
	}
	return 0
}

func (m *Segment) GetPolySpanWidth() uint32 {
	if m != nil {
		return m.PolySpanWidth
	}
	return 0
}

func (m *Segment) GetPolynomials() []float64 {
	if m != nil {
		return m.Polynomials
	}
	return nil
}

func (m *Segment) GetInfo() []uint32 {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Segment) GetWords() []int64 {
	if m != nil {
		return m.Words
	}
	return nil
}

// PolyArray uses one or more polynomial to compress and store an array of int32.
//
// Since 0.5.2
type PolyArray struct {
	N                    int32      `protobuf:"varint,10,opt,name=N,proto3" json:"N,omitempty"`
	Segments             []*Segment `protobuf:"bytes,20,rep,name=Segments,proto3" json:"Segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PolyArray) Reset()         { *m = PolyArray{} }
func (m *PolyArray) String() string { return proto.CompactTextString(m) }
func (*PolyArray) ProtoMessage()    {}
func (*PolyArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_polyarray_42001cec0af51f9f, []int{1}
}
func (m *PolyArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolyArray.Unmarshal(m, b)
}
func (m *PolyArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolyArray.Marshal(b, m, deterministic)
}
func (dst *PolyArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolyArray.Merge(dst, src)
}
func (m *PolyArray) XXX_Size() int {
	return xxx_messageInfo_PolyArray.Size(m)
}
func (m *PolyArray) XXX_DiscardUnknown() {
	xxx_messageInfo_PolyArray.DiscardUnknown(m)
}

var xxx_messageInfo_PolyArray proto.InternalMessageInfo

func (m *PolyArray) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *PolyArray) GetSegments() []*Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func init() {
	proto.RegisterType((*Segment)(nil), "Segment")
	proto.RegisterType((*PolyArray)(nil), "PolyArray")
}

func init() { proto.RegisterFile("polyarray.proto", fileDescriptor_polyarray_42001cec0af51f9f) }

var fileDescriptor_polyarray_42001cec0af51f9f = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0xcf, 0xa9,
	0x4c, 0x2c, 0x2a, 0x4a, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xce, 0xc8, 0xc5,
	0x1e, 0x9c, 0x9a, 0x9e, 0x9b, 0x9a, 0x57, 0x22, 0x24, 0xc5, 0xc5, 0x11, 0x90, 0x9f, 0x53, 0x19,
	0x5c, 0x90, 0x98, 0x27, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe7, 0x0b, 0xa9, 0x70, 0xf1,
	0xc2, 0xd8, 0xe1, 0x99, 0x29, 0x25, 0x19, 0x12, 0x6c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0xa8, 0x82,
	0x42, 0x0a, 0x5c, 0xdc, 0x20, 0x81, 0xbc, 0xfc, 0xdc, 0xcc, 0xc4, 0x9c, 0x62, 0x09, 0x2e, 0x05,
	0x66, 0x0d, 0xc6, 0x20, 0x64, 0x21, 0x21, 0x21, 0x2e, 0x16, 0xcf, 0xbc, 0xb4, 0x7c, 0x09, 0x6e,
	0x05, 0x66, 0x0d, 0xde, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0x3c, 0xbf, 0x28, 0xa5, 0x58,
	0x42, 0x44, 0x81, 0x59, 0x83, 0x39, 0x08, 0xc2, 0x51, 0xb2, 0xe7, 0xe2, 0x04, 0x69, 0x74, 0x04,
	0x39, 0x56, 0x88, 0x87, 0x8b, 0xd1, 0x4f, 0x82, 0x0b, 0xec, 0x26, 0x46, 0x3f, 0x21, 0x15, 0x2e,
	0x0e, 0xa8, 0x9b, 0x21, 0x7a, 0xb8, 0x8d, 0x38, 0xf4, 0xa0, 0x02, 0x41, 0x70, 0x19, 0x27, 0xf6,
	0x28, 0x56, 0xb0, 0x4f, 0x93, 0xd8, 0xc0, 0x5e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2b,
	0x95, 0xc6, 0x36, 0xfd, 0x00, 0x00, 0x00,
}
