// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slimtrie.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SlimTrie struct {
	Children             *Array32 `protobuf:"bytes,1,opt,name=Children,proto3" json:"Children,omitempty"`
	Steps                *Array32 `protobuf:"bytes,2,opt,name=Steps,proto3" json:"Steps,omitempty"`
	Leaves               *Array32 `protobuf:"bytes,3,opt,name=Leaves,proto3" json:"Leaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlimTrie) Reset()         { *m = SlimTrie{} }
func (m *SlimTrie) String() string { return proto.CompactTextString(m) }
func (*SlimTrie) ProtoMessage()    {}
func (*SlimTrie) Descriptor() ([]byte, []int) {
	return fileDescriptor_b09e72937c511537, []int{0}
}

func (m *SlimTrie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlimTrie.Unmarshal(m, b)
}
func (m *SlimTrie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlimTrie.Marshal(b, m, deterministic)
}
func (m *SlimTrie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlimTrie.Merge(m, src)
}
func (m *SlimTrie) XXX_Size() int {
	return xxx_messageInfo_SlimTrie.Size(m)
}
func (m *SlimTrie) XXX_DiscardUnknown() {
	xxx_messageInfo_SlimTrie.DiscardUnknown(m)
}

var xxx_messageInfo_SlimTrie proto.InternalMessageInfo

func (m *SlimTrie) GetChildren() *Array32 {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SlimTrie) GetSteps() *Array32 {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *SlimTrie) GetLeaves() *Array32 {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func init() {
	proto.RegisterType((*SlimTrie)(nil), "SlimTrie")
}

func init() { proto.RegisterFile("slimtrie.proto", fileDescriptor_b09e72937c511537) }

var fileDescriptor_b09e72937c511537 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0xc9, 0xcc,
	0x2d, 0x29, 0xca, 0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4e, 0x2c, 0x2a, 0x4a,
	0xac, 0x84, 0x70, 0x94, 0x8a, 0xb8, 0x38, 0x82, 0x73, 0x32, 0x73, 0x43, 0x8a, 0x32, 0x53, 0x85,
	0x54, 0xb8, 0x38, 0x9c, 0x33, 0x32, 0x73, 0x52, 0x8a, 0x52, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35,
	0xb8, 0x8d, 0x38, 0xf4, 0x1c, 0x41, 0x6a, 0x8d, 0x8d, 0x82, 0xe0, 0x32, 0x42, 0x72, 0x5c, 0xac,
	0xc1, 0x25, 0xa9, 0x05, 0xc5, 0x12, 0x4c, 0x68, 0x4a, 0x20, 0xc2, 0x42, 0x0a, 0x5c, 0x6c, 0x3e,
	0xa9, 0x89, 0x65, 0xa9, 0xc5, 0x12, 0xcc, 0x68, 0x0a, 0xa0, 0xe2, 0x4e, 0xdc, 0x51, 0x9c, 0x60,
	0xcb, 0x4b, 0x2a, 0x0b, 0x52, 0x93, 0xd8, 0xc0, 0x4c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x91, 0xed, 0x9d, 0xa6, 0x00, 0x00, 0x00,
}
