name: test
on:
  push:
  pull_request_target:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version:
            - 1.17.x
            - 1.18.x
        os:
            - ubuntu-latest
            - macos-latest
            - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}

        - name: checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.sha || github.sha }}

        - name: cache
          if: github.event_name == 'push'
          uses: actions/cache@v4
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: cache (read-only)
          if: github.event_name != 'push'
          uses: actions/cache/restore@v4
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: test
          run: |
            make test

        - name: Send coverage
          uses: shogo82148/actions-goveralls@v1
          with:
            path-to-profile: coverage.out
            flag-name: Go-${{ matrix.go }}
            parallel: true
